### ISSUE TITLE
use text input for birtdate

### ISSUE THREAD

**Issue by philippeBron** [cristianpb/covid-19-certificate#44]
with a date input, feeding birthdate is not intuitive with a mobile. change to a simple text input instead.

**Comment by nesk** [comment]
That's why I've created [a date selector in the original project](https://github.com/nesk/covid-19-certificate/blob/master/certificate.js#L152-L154), you can reuse it if you want. It allows the user to enter a date with the keyboard or to select a date with the native date selector by clicking an icon.

Note: you can also leave the `<input type=date>` on iOS, which is way intuitive than the Android one.

**Comment by philippeBron** [comment]
there was a problem with chrome and some browser with this component.

**Comment by philippeBron** [comment]
What about a simple text input with "/" added automatically?

**Comment by nesk** [comment]
Why not, and you could use [the `inputmode="numeric"` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode).
